[build]
  publish = "frontend/out"
  command = "cd frontend && npm ci && npm run build && npm run export"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"